---
apiVersion: v1
offerings:
  - name: deploy-arch-ibm-icd-valkey
    kind: solution
    catalog_id: 7df1e4ca-d54c-4fd0-82ce-3d13247308cd
    offering_id: 8dc75e42-ec8f-4103-a41b-8f41e4562e01
    variations:
      - name: fully-configurable
        mark_ready: true
        install_type: fullstack
        scc:
          instance_id: 1c7d5f78-9262-44c3-b779-b28fe4d88c37
          region: us-south
          scope_resource_group_var_name: existing_resource_group_name
